services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: food-chart-backend
    ports:
      - "5050:5050"
    volumes:
      - ./food_server/model:/app/model:ro
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: food-chart-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
